### PR TITLE
Add function to specify login ID and password

### LINKED ISSUE #152: Option to specify password without specifying wallet address
Hey, first of all thanks for the project.

I'm using `moneroocean.stream`. There, you need to specify the miner ID via the password field. The `userid` parameter for `startMiningWithId` is completely ignored by the pool. I want to distinguish between the users accessing the webpage, so I need to use the `startMining` function to specify the password. But then I'm also forced to specify the wallet address in the frontend.

Is there an option to only specify the password (e.g. by using the third parameter of `startMiningWithId` as the password)?

Thanks in advance.

### PR DESCRIPTION
**Pull request by MexHigh**
Adds the JavaScript function `startMiningWithIdAndPassword(loginid, password, numThreads = -1, userid = "")` (including the backend implementation). 

It can be used if you mine on a pool which does not require a password, but where you must set the miner ID in the password field (like you need on the `moneroocean.stream` pool) to distinguish your miners. The function this PR introduced can then be used, so you don't need to specify your wallet address (username for the pool) and the pool in the frontend. Instead, the `loginid` is used to look them up.

Closes #152

### CODE REVIEW

**Comment by MexHigh** [comment]
I've tested this now, and it works like a charm :)

**Comment by notgiven688** [comment]
Thanks for the PR. @MexHigh . Could we get away with having the following logic in the original if-branch in Program.cs (untested code):

```
if (msg.ContainsKey("loginid"))
{
    (...)

    // prefer message password if specified
    if (msg.ContainsKey("password")) client.Password = msg["password"].GetString();
    else client.Password = crdts.Password;

    (...)
}
```
Maybe this is a bit simpler(?)

**Comment by MexHigh** [comment]
@notgiven688 I thought about this, too. Yeah, maybe it is better to read. I'm going to test this.

**Comment by MexHigh** [comment]
Done :+1:

**Pull request merged**
